### ISSUE TITLE
Safe cast (`:::`) throws `extraneous input` error when running named query

### ISSUE THREAD

**Issue by zkeller89** [malloydata/malloy-py#18]
Hey Folks, 

First time submitting an issue to a project of this caliber so bear with me:

When using the python module to run a named query that uses the safe cast expression (`:::`), I'm getting an `extraneous input ':' expecting {BOOLEAN, DATE, NUMBER, STRING, TIMESTAMP}` error. This doesn't occur when using the normal cast (`::`) expression. I've attached 3 files that make a reasonably minimal reproduction of the error. 

[malloy_error.zip](https://github.com/malloydata/malloy-py/files/11952068/malloy_error.zip)

Here's the contents of my Pipfile if that's useful:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
pandas = "*"
malloy = "*"

[dev-packages]

[requires]
python_version = "3.8"
```

Happy to include any additional info that is helpful. Much thanks!

**Comment by whscullin** [comment]
The malloy package used by malloy-py is out of date and there are breaking changes that are taking a little bit to address, this should be addressed in the next day or so.
