### ISSUE TITLE
Jupyter: UI work on the results.

### ISSUE THREAD

**Issue by lloydtabb** [malloydata/malloy-py#41]
Can you guys work on the UI for the Table renderer?  Feels like the bar is too big,  we need something more light weight.

![image](https://github.com/malloydata/malloy-py/assets/1093458/8e3c6626-5360-4cf9-8be2-0c3cd1bf20a3)

**Comment by tschomer** [comment]
![image](https://github.com/malloydata/malloy-py/assets/40474956/73ad06fe-b02e-459e-b76b-3580da959d32)

**Comment by lloydtabb** [comment]
Why do we need the X and the space there?  

![image](https://github.com/malloydata/malloy-py/assets/1093458/799f71f0-dbd6-4548-91fd-617d6543d82e)

**Comment by srschandan** [comment]
'X' is the close button which I'll remove. 

![Screen Recording 2023-08-28 at 11 49 50 AM](https://github.com/malloydata/malloy-py/assets/10955828/d831dfc7-f0e7-4120-97b4-eb497d9bf0a2)
