### ISSUE TITLE
Suggestion: Add formatting

### ISSUE THREAD

**Issue by Oscmage** [malloydata/malloy-py#7]
Currently the build runs tests but not formatting.

Common within the python community is to use [black](https://pypi.org/project/black/) for formatting. This would address 
`PEP 8: E111 indentation is not a multiple of 4` which is currently a warning I see for the repository.

My suggestion would be that black is ran as part of CI and potentially something you could add together with [pre-commit](https://pre-commit.com/).

**Comment by whscullin** [comment]
For formatting we use Google flavored yapf, which is now enforced by CI: https://github.com/malloydata/malloy-py/pull/14
